// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ajE8biNbkb49vysgFi9SyAu4LE6dzhk',
    appId: '1:1026740021800:web:b85f80d10de3c63511a31d',
    messagingSenderId: '1026740021800',
    projectId: 'ai-study-genie',
    authDomain: 'ai-study-genie.firebaseapp.com',
    storageBucket: 'ai-study-genie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu4QiiMbaHzZGE2ncz38W4mHfMy8FjSuI',
    appId: '1:1026740021800:android:f607b8757ca3f60311a31d',
    messagingSenderId: '1026740021800',
    projectId: 'ai-study-genie',
    storageBucket: 'ai-study-genie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyQnzHXSe5yzTsTczPjsW3Dx5qbaOimVA',
    appId: '1:1026740021800:ios:df35cc238ebc133311a31d',
    messagingSenderId: '1026740021800',
    projectId: 'ai-study-genie',
    storageBucket: 'ai-study-genie.firebasestorage.app',
    iosBundleId: 'com.example.aiStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyQnzHXSe5yzTsTczPjsW3Dx5qbaOimVA',
    appId: '1:1026740021800:ios:df35cc238ebc133311a31d',
    messagingSenderId: '1026740021800',
    projectId: 'ai-study-genie',
    storageBucket: 'ai-study-genie.firebasestorage.app',
    iosBundleId: 'com.example.aiStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ajE8biNbkb49vysgFi9SyAu4LE6dzhk',
    appId: '1:1026740021800:web:d14825a38335d04c11a31d',
    messagingSenderId: '1026740021800',
    projectId: 'ai-study-genie',
    authDomain: 'ai-study-genie.firebaseapp.com',
    storageBucket: 'ai-study-genie.firebasestorage.app',
  );
}
